### ISSUE TITLE
ksvalidator -l should not require file argument

### ISSUE THREAD

**Issue by brianredbeard** [dcantrell/pykickstart#242]
in RHEL7  `ksvalidator -l` requires a file to be passed as  positional argument in order to see the versions which are valid input to `-v`:

```
$ ksvalidator -l
usage: ksvalidator [options] ksfile
ksvalidator: error: too few arguments
$ ksvalidator -l /var/www/html/ks/b64.ks 
DEVEL
F10
F11
F12
F13
F14
F15
F16
F17
F18
F19
F20
F21
F22
F7
F8
F9
FC3
FC4
FC5
FC6
RHEL3
RHEL4
RHEL5
RHEL6
RHEL7
```

This value is spurious and has no impact on the utility:

```
$ ksvalidator -l /dev/null 
DEVEL
F10
F11
F12
F13
F14
F15
F16
F17
F18
F19
F20
F21
F22
F7
F8
F9
FC3
FC4
FC5
FC6
RHEL3
RHEL4
RHEL5
RHEL6
RHEL7
```

**Comment by clumens** [comment]
This is fixed by 761705b4a8bf101c66d8ddafee1177ad5f7795c4 on master.  For RHEL7, unfortunately, I'd need a bug filed at bugzilla.redhat.com and it would need to get approved and ACKed and blah blah blah.  If you don't feel like jumping through all those hoops, you can just grab that commit and apply it locally.  There's not much to it.

**Comment by dcantrell** [comment]
I have opened https://bugzilla.redhat.com/show_bug.cgi?id=1653778 and requested approval for RHEL 7.7 development.

**Comment by dcantrell** [comment]
Closing this as it has been dealt with in RHEL development.
